python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_0_12 0 0 12
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_1_11 0 1 11
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_2_10 0 2 10
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_3_9 0 3 9
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_4_8 0 4 8
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_5_7 0 5 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_6_6 0 6 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_7_5 0 7 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_8_4 0 8 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_9_3 0 9 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_10_2 0 10 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_11_1 0 11 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 0_12_0 0 12 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_0_11 1 0 11
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_1_10 1 1 10
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_2_9 1 2 9
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_3_8 1 3 8
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_4_7 1 4 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_5_6 1 5 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_6_5 1 6 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_7_4 1 7 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_8_3 1 8 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_9_2 1 9 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_10_1 1 10 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 1_11_0 1 11 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_0_10 2 0 10
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_1_9 2 1 9
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_2_8 2 2 8
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_3_7 2 3 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_4_6 2 4 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_5_5 2 5 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_6_4 2 6 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_7_3 2 7 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_8_2 2 8 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_9_1 2 9 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 2_10_0 2 10 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_0_9 3 0 9
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_1_8 3 1 8
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_2_7 3 2 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_3_6 3 3 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_4_5 3 4 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_5_4 3 5 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_6_3 3 6 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_7_2 3 7 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_8_1 3 8 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 3_9_0 3 9 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_0_8 4 0 8
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_1_7 4 1 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_2_6 4 2 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_3_5 4 3 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_4_4 4 4 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_5_3 4 5 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_6_2 4 6 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_7_1 4 7 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 4_8_0 4 8 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_0_7 5 0 7
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_1_6 5 1 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_2_5 5 2 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_3_4 5 3 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_4_3 5 4 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_5_2 5 5 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_6_1 5 6 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 5_7_0 5 7 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_0_6 6 0 6
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_1_5 6 1 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_2_4 6 2 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_3_3 6 3 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_4_2 6 4 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_5_1 6 5 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 6_6_0 6 6 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_0_5 7 0 5
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_1_4 7 1 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_2_3 7 2 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_3_2 7 3 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_4_1 7 4 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 7_5_0 7 5 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 8_0_4 8 0 4
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 8_1_3 8 1 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 8_2_2 8 2 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 8_3_1 8 3 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 8_4_0 8 4 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 9_0_3 9 0 3
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 9_1_2 9 1 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 9_2_1 9 2 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 9_3_0 9 3 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 10_0_2 10 0 2
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 10_1_1 10 1 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 10_2_0 10 2 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 11_0_1 11 0 1
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 11_1_0 11 1 0
python choose_checkpoint.py ../model_transformer_encz.base.block_40k.results_comet 12_0_0 12 0 0
